config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'rooms#index'
  resources :rooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit -> { broadcast_append_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    room = Room.find(params[:room_id])
    room.messages.create!(**message_params, user: current_user)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to room }
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user! # Deviseのログイン確認

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActioncableRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div><%= message.content %></div>

app/views/rooms/_room.html.erb
<div><%= link_to room.name, room_path(room) %></div>

app/views/rooms/index.html.erb
<h1>Room select</h1>

<%= render @rooms %>

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<%= turbo_stream_from @room %>

<div id='messages'>
  <%= render @room.messages %>
</div>

<%= form_with(model: [@room, @room.messages.new], data: { controller: "form", action: "turbo:submit-end->form#reset" }) do |f| %>
  <%= f.label :content, 'Say something:' %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>